# Numpy Library

- Processing N-Dimentional Array



In [4]:
import numpy as np
li = [1,2,3]
a = np.array(li)
type(a)

numpy.ndarray

In [5]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
rn = np.random.randint(0,10,size=10)
rn

array([9, 0, 4, 3, 4, 4, 1, 6, 3, 5])

In [33]:
rn = np.random.randint(0,10,size = (3,3,3,3))
rn #[2][2][2][1]

array([[[[1, 3, 6],
         [4, 1, 2],
         [6, 9, 4]],

        [[3, 9, 6],
         [7, 8, 8],
         [4, 1, 7]],

        [[0, 0, 6],
         [9, 3, 4],
         [3, 2, 0]]],


       [[[8, 2, 0],
         [1, 6, 0],
         [3, 9, 9]],

        [[0, 4, 4],
         [9, 3, 5],
         [2, 4, 7]],

        [[6, 5, 8],
         [9, 5, 1],
         [7, 9, 8]]],


       [[[3, 6, 9],
         [6, 2, 4],
         [1, 2, 4]],

        [[2, 1, 9],
         [4, 5, 4],
         [7, 3, 7]],

        [[8, 1, 4],
         [0, 7, 5],
         [7, 1, 1]]]])

In [34]:
rn.ndim
rn.size
rn.shape

(3, 3, 3, 3)

In [35]:
rn.dtype

dtype('int32')

In [36]:
rn.itemsize

4

In [37]:
rn.nbytes

324

In [38]:
rn[2,-1]

array([[8, 1, 4],
       [0, 7, 5],
       [7, 1, 1]])

In [40]:
rn[0,0]= 12
rn

array([[[[12, 12, 12],
         [12, 12, 12],
         [12, 12, 12]],

        [[ 3,  9,  6],
         [ 7,  8,  8],
         [ 4,  1,  7]],

        [[ 0,  0,  6],
         [ 9,  3,  4],
         [ 3,  2,  0]]],


       [[[ 8,  2,  0],
         [ 1,  6,  0],
         [ 3,  9,  9]],

        [[ 0,  4,  4],
         [ 9,  3,  5],
         [ 2,  4,  7]],

        [[ 6,  5,  8],
         [ 9,  5,  1],
         [ 7,  9,  8]]],


       [[[ 3,  6,  9],
         [ 6,  2,  4],
         [ 1,  2,  4]],

        [[ 2,  1,  9],
         [ 4,  5,  4],
         [ 7,  3,  7]],

        [[ 8,  1,  4],
         [ 0,  7,  5],
         [ 7,  1,  1]]]])

In [47]:
x = np.random.randint(0,10,size = (3,4))
x

array([[5, 5, 4, 4],
       [7, 6, 0, 3],
       [6, 9, 7, 8]])

In [49]:
x[:5]

array([[5, 5, 4, 4],
       [7, 6, 0, 3],
       [6, 9, 7, 8]])

In [48]:
x[:2, :3]

array([[5, 5, 4],
       [7, 6, 0]])

In [50]:
x[:3, ::2]

array([[5, 4],
       [7, 0],
       [6, 7]])

In [51]:
x[::-1,::-1]

array([[8, 7, 9, 6],
       [3, 0, 6, 7],
       [4, 4, 5, 5]])

In [52]:
print(x[:3, ::2])

[[5 4]
 [7 0]
 [6 7]]


In [53]:
print(x[0,:])

[5 5 4 4]


#### Let's Extract 2*2 subtract  from other

In [61]:
x2_sub = x[:2, :2]
x2_sub

array([[5, 5],
       [7, 6]])

In [66]:
rn.reshape(1,1)

ValueError: cannot reshape array of size 9 into shape (1,1)

In [72]:
a = np.array([0,1,2,3])
b = np.array([5,5,5,5])
c = np.array([10,10,10,10])
print(a+b)
print(a+10)
print(a+b+c)

[5 6 7 8]
[10 11 12 13]
[15 16 17 18]


In [75]:
a = np.array([0,1,2,3],[5,5,5,5])
b = np.array([5,5,5,5],[5,5,5,5])
c = np.array([10,10,10,10],[5,5,5,5])
print(a+b)

TypeError: data type not understood

In [76]:
m = np.ones(5)
print(m)

[1. 1. 1. 1. 1.]


## Pandas
**Use cases**
- Data Analysis
- Data Cleaning
- Data Transformation

**Notations**

- Series
- DataFrames

In [79]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':20}
internal1 = pd.Series(internal1)

internal1
internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)

internal2



s1    15
s2    18
s3    12
dtype: int64

In [84]:
final = pd.DataFrame({'Internal1':internal1,'Internal2':internal2})
final


Internal1  Internal2
s1         21         15
s2         18         18
s3         20         12

In [90]:
final['Internal1']

s1    21
s2    18
s3    20
Name: Internal1, dtype: int64

In [87]:
final.columns    # Names of all columns 

Index(['Internal1', 'Internal2'], dtype='object')

In [91]:
final.values      # Lists of all rows

array([[21, 15],
       [18, 18],
       [20, 12]], dtype=int64)

In [92]:
final.values[2]

array([20, 12], dtype=int64)

In [93]:
final.values[2,0]

20

In [94]:
final.values[2][0]

20

In [97]:
for row in final.values:
    print('Internal-',row[0],'Internal2-',row[1])

Internal- 21 Internal2- 15
Internal- 18 Internal2- 18
Internal- 20 Internal2- 12


In [98]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         20         12

In [103]:
final.loc['s4'] = [25,18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         15         18
3          15         18
s4         25         18

In [104]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         18
s3         15         18
s4         25         18

In [106]:
final =final.drop(3)

In [107]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         15         18
s4         25         18

In [108]:
final.values[2] = [12,25]

In [109]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         12         25
s4         25         18

In [35]:
s = 'shameem'
s

'shameem'

In [36]:
print(s[::-2])

meas


In [37]:
print(s[::-1])

meemahs
